
# Build the hyrax-dependencies for the same architecture as OPeNDAP developer
# machines, to ensure changes to repository are valid for dev machines.

on:
  # For now, run only on manually triggered builds (workflow_dispatch).
  # Uncomment the "push" and "pull_request" to build on all non-draft PRs
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - /^(.*-test-deploy)$/
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
concurrency:
  # Cancel intermediate builds only on pull requests
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    # Run on pushes or non-draft PRs
    if: (github.event_name == 'push') || (github.event.pull_request.draft == false) || (github.event_name == 'workflow_dispatch')
    name: Build on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          # See https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md for pre-installed software
          - macos-15
          - macos-15-intel
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          brew install bison \
                       openssl \
                       jpeg \
                       cppunit \
                       autoconf \
                       automake \
                       libgeotiff \
                       ninja \
                       go
        shell: bash
      - name: Build hyrax-dependencies
        run: |
            export prefix=$HOME/install
            make for-travis -j16
        shell: bash
        env:
          extra_targets: "aws_s2n_tls aws_lc aws_cdk"
      - name: List built dependencies
        run: make list-built
        shell: bash
      - name: Confirm all dependencies are built
        run: ./travis/check-installed $EXPECTED_DEPS_COUNT
        shell: bash
        env:
          # GDAL currently doesn't build on m-chip, ref #93
          EXPECTED_DEPS_COUNT: "${{ matrix.runs-on == 'macos-15' && 13 || 14 }}"
