
# Build the hyrax-dependencies for the same architecture as OPeNDAP developer
# machines, to ensure changes to repository are valid for dev machines.

on:
  # For now, run only on manually triggered builds (workflow_dispatch).
  # Uncomment the "push" and "pull_request" to build on all non-draft PRs
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - /^(.*-test-deploy)$/
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
concurrency:
  # Cancel intermediate builds only on pull requests
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  build:
    # Run on pushes or non-draft PRs
    if: (github.event_name == 'push') || (github.event.pull_request.draft == false) || (github.event_name == 'workflow_dispatch')
    name: Build on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          # See https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md for pre-installed software
          - macos-15
          - macos-15-intel
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          brew install bison \
                       openssl \
                       jpeg \
                       cppunit \
                       autoconf \
                       automake \
                       libgeotiff
        shell: bash
      - name: Build hyrax-dependencies
        run: |
            export prefix=$HOME/install
            make for-travis -j16
        shell: bash
        env:
          extra_targets: ""
      - name: List built dependencies
        run: make list-built
        shell: bash
      - name: Confirm all dependencies are built
        run: ./travis/check-installed $EXPECTED_DEPS_COUNT
        shell: bash
        env:
          # GDAL currently doesn't build on m-chip, ref #93
          EXPECTED_DEPS_COUNT: "${{ matrix.runs-on == 'macos-15' && 11 || 12 }}"
      - name: Generate tarball
        run: |
          mkdir -vp ${{ github.workspace }}/package
          echo "# ${{ matrix.runs-on }} - TARBALL_NUMBERED '$TARBALL_NUMBERED'" >&2
          echo "# ubuntu-focal - TARBALL_LATEST '$TARBALL_LATEST'" >&2
          tar -C "$HOME" -czvf "$TARBALL_NUMBERED" install
          cp -v "$TARBALL_NUMBERED" "$TARBALL_LATEST"
        shell: bash
        env:
          TARBALL_NUMBERED: "${{ github.workspace }}/package/hyrax-dependencies-${{ matrix.runs-on }}-${{ github.run_number }}.tgz"
          TARBALL_LATEST: "${{ github.workspace }}/package/hyrax-dependencies-${{ matrix.runs-on }}.tgz"
      - name: Deploy to s3
        # Will be a dryrun except for "push" triggers, which will only occur on
        # main or master branch as defined by the workflow itself
        run: |
          aws s3 cp ${{ github.workspace }}/package s3://opendap.travis.build $aws_options
        shell: bash
        env:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_options: "${{ github.event_name == 'push' && '' || '--dryrun' }}"
